---
- name: install pureftpd
  apt:
   name={{ item }}   state=present
  with_items:
    - pure-ftpd-common
    - pure-ftpd-mysql
    - quota
    - quotatool

- name: set chroot
  replace:
    dest: /etc/default/pure-ftpd-common
    regexp: '^VIRTUALCHROOT=false'
    replace: 'VIRTUALCHROOT=true'
